apiVersion: apps/v1
kind: Deployment
metadata:
  name: upteck-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upteck-front
  template:
    metadata:
      labels:
        app: upteck-front
    spec:
      containers:
      - name: upteck-front
        image: raykadri/upteck_crud_angular-app:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.3"
      restartPolicy: Always
